"""AVAROS data loader for PREVENTION platform.

Loads manufacturing KPI time-series data from JSON files into MongoDB.
Data files are exported from RENERYO (or generated by reneryo-data-generator)
and stored in the addon's data/ directory.

Follows PREVENTION's DataLoad ABC pattern (clean_data / load_data).
"""

import os
import urllib.parse

import pandas as pd
from core.initialization import DataLoad
from core.utils.datasources.mongo import mongo_utils
from pymongo import MongoClient


ADDON_NAME = "avaros"

DATA_FILES = [
    "energy_metrics.json",
    "production_metrics.json",
    "material_metrics.json",
    "carbon_metrics.json",
    "supplier_metrics.json",
]

DATABASES_TO_CLEAN = [
    "init_data",
    "prevention",
    ADDON_NAME,
    f"{ADDON_NAME}-results",
]


class AvarosDataLoad(DataLoad):
    """Load AVAROS manufacturing KPI data into PREVENTION MongoDB."""

    def __init__(self):
        cwd = os.getcwd()
        self.data_path = f"{cwd}/addons/{ADDON_NAME}/data/"
        self.collection_name = "kpi_metrics"
        self.id_column = "id"
        self.date_column = "timestamp"

    def clean_data(self):
        """Drop all AVAROS-related MongoDB collections."""
        for db_name in DATABASES_TO_CLEAN:
            mongo_utils.drop_all_collections(db_name)

    def load_data(self):
        """Load all KPI JSON files into a single MongoDB collection."""
        print(f"[AVAROS] Loading data from {self.data_path}")

        frames = []
        for filename in DATA_FILES:
            filepath = self.data_path + filename
            if not os.path.exists(filepath):
                print(f"[AVAROS] WARNING: {filepath} not found, skipping")
                continue
            df = pd.read_json(filepath)
            frames.append(df)
            print(f"[AVAROS] Loaded {len(df)} records from {filename}")

        if not frames:
            print("[AVAROS] No data files found — addon will have no data")
            return

        combined = pd.concat(frames, ignore_index=True)
        combined = combined.drop_duplicates(subset=self.id_column, keep="first")
        combined = combined.dropna(how="all")
        combined = combined.sort_values(by=self.date_column)

        _insert_to_mongo(
            combined,
            id_column=self.id_column,
            collection_name=self.collection_name,
            db_name="init_data",
        )
        print(f"[AVAROS] Inserted {len(combined)} total records into MongoDB")


def _insert_to_mongo(
    df: pd.DataFrame,
    id_column: str,
    collection_name: str,
    db_name: str,
) -> None:
    """Insert a DataFrame into MongoDB with deduplication index."""
    client = MongoClient(
        f"mongodb://{mongo_utils.mongo_username}:"
        f"{urllib.parse.quote_plus(mongo_utils.mongo_pass)}"
        f"@{mongo_utils.mongo_host}:{int(mongo_utils.mongo_port)}/"
    )
    database = client[db_name]
    col = database[collection_name]
    col.create_index(id_column, unique=True)

    records = df.to_dict(orient="records")
    if records:
        col.insert_many(records)
