#!/usr/bin/env python3
"""Generate a pre-reset audit snapshot for AVAROS + Reneryo.

Outputs two files under docs/reset-precheck/:
- JSON report (machine-readable)
- Markdown summary (human-readable)

The report intentionally excludes sensitive secret values.
"""

from __future__ import annotations

import json
import ssl
from dataclasses import asdict, dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any
from urllib.error import URLError, HTTPError
from urllib.parse import urlencode
from urllib.request import Request, urlopen


REPO_ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = REPO_ROOT / ".env"
OUTPUT_DIR = REPO_ROOT / "docs" / "reset-precheck"


@dataclass(frozen=True)
class ApiCallResult:
    """HTTP call result summary."""

    ok: bool
    status: int | None
    error: str
    data: dict[str, Any] | list[Any] | None


def _load_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def _call_json(
    url: str,
    headers: dict[str, str] | None = None,
    *,
    verify_ssl: bool = True,
    timeout: int = 25,
) -> ApiCallResult:
    try:
        req = Request(url, headers=headers or {})
        context = ssl.create_default_context() if verify_ssl else ssl._create_unverified_context()
        with urlopen(req, context=context, timeout=timeout) as response:
            body = response.read().decode("utf-8")
            payload = json.loads(body) if body else {}
            return ApiCallResult(ok=True, status=response.status, error="", data=payload)
    except HTTPError as exc:
        return ApiCallResult(ok=False, status=exc.code, error=f"HTTPError: {exc}", data=None)
    except URLError as exc:
        return ApiCallResult(ok=False, status=None, error=f"URLError: {exc}", data=None)
    except Exception as exc:  # pragma: no cover - defensive
        return ApiCallResult(ok=False, status=None, error=f"{type(exc).__name__}: {exc}", data=None)


def _reneryo_headers(env: dict[str, str]) -> tuple[dict[str, str], str]:
    token = env.get("RENERYO_API_TOKEN", "").strip()
    if token:
        return {"X-Token": token}, "token"

    cookie = env.get("RENERYO_SESSION_COOKIE", "").strip()
    if cookie:
        if not cookie.startswith("S="):
            cookie = f"S={cookie}"
        return {"Cookie": cookie}, "cookie"

    return {}, "none"


def _get_records(payload: dict[str, Any] | list[Any] | None) -> list[dict[str, Any]]:
    if payload is None:
        return []
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]
    records = payload.get("records", [])
    if isinstance(records, list):
        return [item for item in records if isinstance(item, dict)]
    return []


def _build_markdown(report: dict[str, Any]) -> str:
    avaros = report["avaros"]
    reneryo = report["reneryo"]

    lines: list[str] = []
    lines.append("# Reneryo Pre-Reset Audit Snapshot")
    lines.append("")
    lines.append(f"- Timestamp (UTC): {report['timestamp_utc']}")
    lines.append(f"- Generated by: scripts/pre_reset_reneryo_audit.py")
    lines.append("")
    lines.append("## AVAROS")
    lines.append(f"- API base: {avaros['api_base']}")
    lines.append(f"- Reachable: {avaros['reachable']}")
    lines.append(f"- Platform type: {avaros['platform_type']}")
    lines.append(f"- Platform auth type: {avaros['platform_auth_type']}")
    lines.append(f"- Asset count: {avaros['asset_count']}")
    lines.append(f"- Metric resources total: {avaros['metric_resources_total']}")
    lines.append(f"- Manual metric mappings: {avaros['manual_metric_mapping_count']}")
    lines.append("")
    lines.append("## Reneryo")
    lines.append(f"- API base: {reneryo['api_base']}")
    lines.append(f"- Reachable: {reneryo['reachable']}")
    lines.append(f"- Auth mode used: {reneryo['auth_mode_used']}")
    lines.append(f"- Total metrics: {reneryo['total_metrics']}")
    lines.append(f"- AVAROS metrics: {reneryo['avaros_metrics_total']}")
    lines.append(f"- AVAROS per-asset metrics (:: Line-*): {reneryo['avaros_with_asset_suffix']}")
    lines.append(f"- AVAROS legacy/non-suffixed metrics: {reneryo['avaros_without_asset_suffix']}")
    lines.append(f"- Non-AVAROS metrics: {reneryo['non_avaros_metrics']}")

    sampled = reneryo.get("sampled_resources", [])
    if sampled:
        lines.append("")
        lines.append("## Sampled Resource Record Counts")
        for item in sampled:
            lines.append(
                "- "
                f"{item['metric_name']} -> resources={item['resource_count']}, "
                f"record_count={item['record_count']}"
            )

    return "\n".join(lines) + "\n"


def main() -> int:
    env = _load_env(ENV_PATH)
    timestamp = datetime.now(timezone.utc)
    stamp = timestamp.strftime("%Y%m%d-%H%M%SZ")

    avaros_base = env.get("AVAROS_WEB_API_BASE", "https://avaros.int.arti.ac/api/v1").rstrip("/")
    avaros_key = env.get("AVAROS_WEB_API_KEY", "").strip()
    avaros_headers = {"X-API-Key": avaros_key} if avaros_key else {}

    reneryo_base = env.get("RENERYO_API_URL", "http://deploys.int.arti.ac:30377/api").rstrip("/")
    reneryo_headers, reneryo_auth_mode = _reneryo_headers(env)

    avaros_status = _call_json(f"{avaros_base}/status", headers=avaros_headers, verify_ssl=False)
    avaros_platform = _call_json(f"{avaros_base}/config/platform", headers=avaros_headers, verify_ssl=False)
    avaros_assets = _call_json(f"{avaros_base}/assets/mappings", headers=avaros_headers, verify_ssl=False)
    avaros_metrics = _call_json(f"{avaros_base}/config/metrics", headers=avaros_headers, verify_ssl=False)

    asset_mappings = {}
    if avaros_assets.ok and isinstance(avaros_assets.data, dict):
        payload = avaros_assets.data.get("asset_mappings", {})
        if isinstance(payload, dict):
            asset_mappings = payload

    metric_resources_total = 0
    for value in asset_mappings.values():
        if not isinstance(value, dict):
            continue
        metric_resources = value.get("metric_resources", {})
        if isinstance(metric_resources, dict):
            metric_resources_total += len(metric_resources)

    manual_metric_mapping_count = 0
    if avaros_metrics.ok:
        if isinstance(avaros_metrics.data, list):
            manual_metric_mapping_count = len(avaros_metrics.data)
        elif isinstance(avaros_metrics.data, dict):
            root = avaros_metrics.data.get("root", [])
            if isinstance(root, list):
                manual_metric_mapping_count = len(root)

    reneryo_metric_list = _call_json(
        f"{reneryo_base}/u/measurement/metric/item?count=500",
        headers=reneryo_headers,
        verify_ssl=True,
    )

    all_metrics = _get_records(reneryo_metric_list.data if reneryo_metric_list.ok else None)
    avaros_metrics_list = [
        item for item in all_metrics
        if str(item.get("name", "")).startswith("AVAROS")
    ]
    avaros_with_suffix = [
        item for item in avaros_metrics_list
        if "::" in str(item.get("name", ""))
    ]
    avaros_without_suffix = [
        item for item in avaros_metrics_list
        if "::" not in str(item.get("name", ""))
    ]
    non_avaros = [
        item for item in all_metrics
        if not str(item.get("name", "")).startswith("AVAROS")
    ]

    sampled_resources: list[dict[str, Any]] = []
    end = datetime.now(timezone.utc)
    start = end - timedelta(days=120)

    for metric in avaros_with_suffix[:3]:
        metric_id = str(metric.get("id", ""))
        metric_name = str(metric.get("name", ""))
        if not metric_id:
            continue

        resources_result = _call_json(
            f"{reneryo_base}/u/measurement/metric/resources?metricId={metric_id}",
            headers=reneryo_headers,
            verify_ssl=True,
        )
        resources = _get_records(resources_result.data if resources_result.ok else None)

        record_count = None
        if resources:
            resource_id = str(resources[0].get("id", ""))
            if resource_id:
                query = urlencode(
                    {
                        "period": "RAW",
                        "count": 100,
                        "page": 1,
                        "datetimeMin": start.isoformat().replace("+00:00", "Z"),
                        "datetimeMax": end.isoformat().replace("+00:00", "Z"),
                    }
                )
                values_result = _call_json(
                    f"{reneryo_base}/u/measurement/metric/resource/{resource_id}/values?{query}",
                    headers=reneryo_headers,
                    verify_ssl=True,
                )
                if values_result.ok and isinstance(values_result.data, dict):
                    record_count = values_result.data.get("recordCount")

        sampled_resources.append(
            {
                "metric_name": metric_name,
                "resource_count": len(resources),
                "record_count": record_count,
            }
        )

    report = {
        "timestamp_utc": timestamp.isoformat().replace("+00:00", "Z"),
        "avaros": {
            "api_base": avaros_base,
            "reachable": avaros_status.ok,
            "status_http": avaros_status.status,
            "platform_http": avaros_platform.status,
            "assets_http": avaros_assets.status,
            "metrics_http": avaros_metrics.status,
            "platform_type": (
                avaros_platform.data.get("platform_type", "")
                if isinstance(avaros_platform.data, dict)
                else ""
            ),
            "platform_auth_type": (
                (avaros_platform.data.get("extra_settings", {}) or {}).get("auth_type", "")
                if isinstance(avaros_platform.data, dict)
                else ""
            ),
            "asset_count": len(asset_mappings),
            "metric_resources_total": metric_resources_total,
            "manual_metric_mapping_count": manual_metric_mapping_count,
            "errors": {
                "status": avaros_status.error,
                "platform": avaros_platform.error,
                "assets": avaros_assets.error,
                "metrics": avaros_metrics.error,
            },
        },
        "reneryo": {
            "api_base": reneryo_base,
            "reachable": reneryo_metric_list.ok,
            "metric_list_http": reneryo_metric_list.status,
            "auth_mode_used": reneryo_auth_mode,
            "total_metrics": len(all_metrics),
            "avaros_metrics_total": len(avaros_metrics_list),
            "avaros_with_asset_suffix": len(avaros_with_suffix),
            "avaros_without_asset_suffix": len(avaros_without_suffix),
            "non_avaros_metrics": len(non_avaros),
            "non_avaros_metric_names": [str(item.get("name", "")) for item in non_avaros],
            "sampled_resources": sampled_resources,
            "errors": {
                "metric_list": reneryo_metric_list.error,
            },
        },
    }

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    json_path = OUTPUT_DIR / f"reneryo-pre-reset-{stamp}.json"
    md_path = OUTPUT_DIR / f"reneryo-pre-reset-{stamp}.md"

    json_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    md_path.write_text(_build_markdown(report), encoding="utf-8")

    print(f"Wrote {json_path}")
    print(f"Wrote {md_path}")
    print("Summary:")
    print(
        json.dumps(
            {
                "avaros_metric_resources_total": report["avaros"]["metric_resources_total"],
                "reneryo_total_metrics": report["reneryo"]["total_metrics"],
                "reneryo_avaros_metrics_total": report["reneryo"]["avaros_metrics_total"],
                "reneryo_non_avaros_metrics": report["reneryo"]["non_avaros_metrics"],
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
